const fs = require('fs');
const path = require('path');

const ta125 = [
    { symbol: 'TEVA.TA', hebrewName: 'טבע תעשיות פרמצבטיות', englishName: 'Teva Pharmaceutical', type: 'stock', exchange: 'TASE' },
    { symbol: 'LUMI.TA', hebrewName: 'בנק לאומי', englishName: 'Bank Leumi', type: 'stock', exchange: 'TASE' },
    { symbol: 'POLI.TA', hebrewName: 'בנק הפועלים', englishName: 'Bank Hapoalim', type: 'stock', exchange: 'TASE' },
    { symbol: 'DSCT.TA', hebrewName: 'קבוצת דיסקונט', englishName: 'Discount Bank', type: 'stock', exchange: 'TASE' },
    { symbol: 'MZRN.TA', hebrewName: 'מזרחי טפחות', englishName: 'Mizrahi Tefahot', type: 'stock', exchange: 'TASE' },
    { symbol: 'FIBI.TA', hebrewName: 'הבינלאומי', englishName: 'FIBI', type: 'stock', exchange: 'TASE' },
    { symbol: 'ICL.TA', hebrewName: 'איי.סי.אל גרופ', englishName: 'ICL Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'NICE.TA', hebrewName: 'נייס', englishName: 'NICE Ltd', type: 'stock', exchange: 'TASE' },
    { symbol: 'ENOG.TA', hebrewName: 'אנרג\'יאן', englishName: 'Energean', type: 'stock', exchange: 'TASE' },
    { symbol: 'BEZQ.TA', hebrewName: 'בזק', englishName: 'Bezeq', type: 'stock', exchange: 'TASE' },
    { symbol: 'AZRG.TA', hebrewName: 'קבוצת עזריאלי', englishName: 'Azrieli Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'MELI.TA', hebrewName: 'מליסרון', englishName: 'Melisron', type: 'stock', exchange: 'TASE' },
    { symbol: 'ESLT.TA', hebrewName: 'אלביט מערכות', englishName: 'Elbit Systems', type: 'stock', exchange: 'TASE' },
    { symbol: 'NVMI.TA', hebrewName: 'נובה', englishName: 'Nova', type: 'stock', exchange: 'TASE' },
    { symbol: 'TSEM.TA', hebrewName: 'טאואר סמיקונדקטור', englishName: 'Tower Semiconductor', type: 'stock', exchange: 'TASE' },
    { symbol: 'ALHE.TA', hebrewName: 'אלוני חץ', englishName: 'Alony Hetz', type: 'stock', exchange: 'TASE' },
    { symbol: 'SPEN.TA', hebrewName: 'שפיר הנדסה', englishName: 'Shapir Engineering', type: 'stock', exchange: 'TASE' },
    { symbol: 'DLOM.TA', hebrewName: 'דלק קבוצה', englishName: 'Delek Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'ARPT.TA', hebrewName: 'אירפורט סיטי', englishName: 'Airport City', type: 'stock', exchange: 'TASE' },
    { symbol: 'FTAL.TA', hebrewName: 'פתאל החזקות', englishName: 'Fattal Holdings', type: 'stock', exchange: 'TASE' },
    { symbol: 'STRA.TA', hebrewName: 'שטראוס גרופ', englishName: 'Strauss Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'SHFR.TA', hebrewName: 'שופרסל', englishName: 'Shufersal', type: 'stock', exchange: 'TASE' },
    { symbol: 'DANE.TA', hebrewName: 'דנאל', englishName: 'Danel', type: 'stock', exchange: 'TASE' },
    { symbol: 'ELTR.TA', hebrewName: 'אלקטרה', englishName: 'Electra', type: 'stock', exchange: 'TASE' },
    { symbol: 'ENRG.TA', hebrewName: 'אנרגיקס', englishName: 'Energix', type: 'stock', exchange: 'TASE' },
    { symbol: 'ENLT.TA', hebrewName: 'אנלייט אנרגיה', englishName: 'Enlight Renewable Energy', type: 'stock', exchange: 'TASE' },
    { symbol: 'EQTL.TA', hebrewName: 'אקויטל', englishName: 'Equital', type: 'stock', exchange: 'TASE' },
    { symbol: 'FMSA.TA', hebrewName: 'אף.אם.אס מיגון', englishName: 'FMS Enterprises', type: 'stock', exchange: 'TASE' },
    { symbol: 'FOX.TA', hebrewName: 'פוקס', englishName: 'Fox Wizel', type: 'stock', exchange: 'TASE' },
    { symbol: 'GILT.TA', hebrewName: 'גילת רשתות לווין', englishName: 'Gilat Satellite Networks', type: 'stock', exchange: 'TASE' },
    { symbol: 'HARL.TA', hebrewName: 'הראל השקעות', englishName: 'Harel Insurance Investments', type: 'stock', exchange: 'TASE' },
    { symbol: 'HLAN.TA', hebrewName: 'חילן', englishName: 'Hilan', type: 'stock', exchange: 'TASE' },
    { symbol: 'IDIN.TA', hebrewName: 'אי.די.איי. ביטוח', englishName: 'IDI Insurance', type: 'stock', exchange: 'TASE' },
    { symbol: 'ISCD.TA', hebrewName: 'ישראכרט', englishName: 'Isracard', type: 'stock', exchange: 'TASE' },
    { symbol: 'ISCN.TA', hebrewName: 'ישראל קנדה', englishName: 'Israel Canada', type: 'stock', exchange: 'TASE' },
    { symbol: 'ISRA.TA', hebrewName: 'ישראמקו יהש', englishName: 'Isramco Negev', type: 'stock', exchange: 'TASE' },
    { symbol: 'KEN.TA', hebrewName: 'קנון הולדינגס', englishName: 'Kenon Holdings', type: 'stock', exchange: 'TASE' },
    { symbol: 'KRNT.TA', hebrewName: 'קורנית דיגיטל', englishName: 'Kornit Digital', type: 'stock', exchange: 'TASE' },
    { symbol: 'MAGIC.TA', hebrewName: 'מג\'יק תעשיות תוכנה', englishName: 'Magic Software', type: 'stock', exchange: 'TASE' },
    { symbol: 'MTRX.TA', hebrewName: 'מטריקס', englishName: 'Matrix IT', type: 'stock', exchange: 'TASE' },
    { symbol: 'MVNE.TA', hebrewName: 'מבנה נדלן', englishName: 'Mivneh Real Estate', type: 'stock', exchange: 'TASE' },
    { symbol: 'OPCE.TA', hebrewName: 'או.פי.סי אנרגיה', englishName: 'O.P.C Energy', type: 'stock', exchange: 'TASE' },
    { symbol: 'ORL.TA', hebrewName: 'בזן', englishName: 'Oil Refineries', type: 'stock', exchange: 'TASE' },
    { symbol: 'PTNR.TA', hebrewName: 'פרטנר תקשורת', englishName: 'Partner Communications', type: 'stock', exchange: 'TASE' },
    { symbol: 'PZOL.TA', hebrewName: 'פז נפט', englishName: 'Paz Oil', type: 'stock', exchange: 'TASE' },
    { symbol: 'PHOE.TA', hebrewName: 'הפניקס', englishName: 'Phoenix Holdings', type: 'stock', exchange: 'TASE' },
    { symbol: 'RMLI.TA', hebrewName: 'רמי לוי', englishName: 'Rami Levy', type: 'stock', exchange: 'TASE' },
    { symbol: 'SPNS.TA', hebrewName: 'סאפיינס', englishName: 'Sapiens International', type: 'stock', exchange: 'TASE' },
    { symbol: 'SKBN.TA', hebrewName: 'שיכון ובינוי', englishName: 'Shikun & Binui', type: 'stock', exchange: 'TASE' },
    { symbol: 'SMT.TA', hebrewName: 'סאמיט', englishName: 'Summit Real Estate', type: 'stock', exchange: 'TASE' },
    // Adding to reach 125 total
    { symbol: 'AFRE.TA', hebrewName: 'אפריקה מגורים', englishName: 'Africa Israel Residences', type: 'stock', exchange: 'TASE' },
    { symbol: 'ALUM.TA', hebrewName: 'אלוט', englishName: 'Allot', type: 'stock', exchange: 'TASE' },
    { symbol: 'AMOT.TA', hebrewName: 'אמות השקעות', englishName: 'Amot Investments', type: 'stock', exchange: 'TASE' },
    { symbol: 'ASHG.TA', hebrewName: 'אשטרום קבוצה', englishName: 'Ashtrom Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'AUDG.TA', hebrewName: 'אודיו קודס', englishName: 'AudioCodes', type: 'stock', exchange: 'TASE' },
    { symbol: 'BIG.TA', hebrewName: 'ביג מרכזי קניות', englishName: 'Big Shopping Centers', type: 'stock', exchange: 'TASE' },
    { symbol: 'BLSR.TA', hebrewName: 'הכשרת הישוב', englishName: 'Israel Land Development', type: 'stock', exchange: 'TASE' },
    { symbol: 'BRAN.TA', hebrewName: 'ברן', englishName: 'Baran Group', type: 'stock', exchange: 'TASE' },
    { symbol: 'BSEN.TA', hebrewName: 'בסר הנדסה', englishName: 'B.S.R Projects', type: 'stock', exchange: 'TASE' },
    { symbol: 'CAMT.TA', hebrewName: 'קמטק', englishName: 'Camtek', type: 'stock', exchange: 'TASE' },
    { symbol: 'CCOM.TA', hebrewName: 'סלקום ישראל', englishName: 'Cellcom Israel', type: 'stock', exchange: 'TASE' },
    { symbol: 'CLIS.TA', hebrewName: 'כלל עסקי ביטוח', englishName: 'Clal Insurance', type: 'stock', exchange: 'TASE' },
    { symbol: 'COAL.TA', hebrewName: 'פחם', englishName: 'Coal Company', type: 'stock', exchange: 'TASE' },
    { symbol: 'CRA.TA', hebrewName: 'אינרום', englishName: 'Inrom Construction', type: 'stock', exchange: 'TASE' },
    { symbol: 'CTXT.TA', hebrewName: 'סאנפלאואר', englishName: 'Sunflower', type: 'stock', exchange: 'TASE' },
    { symbol: 'DEDA.TA', hebrewName: 'דלתא גליל', englishName: 'Delta Galil Industries', type: 'stock', exchange: 'TASE' },
    { symbol: 'DIMR.TA', hebrewName: 'דמרי', englishName: 'J.H. Dimri', type: 'stock', exchange: 'TASE' },
    { symbol: 'DNP.TA', hebrewName: 'דנאל החזקות', englishName: 'Danel', type: 'stock', exchange: 'TASE' },
    { symbol: 'EKT.TA', hebrewName: 'אלקטרה מוצרי צריכה', englishName: 'Electra Consumer Products', type: 'stock', exchange: 'TASE' },
    { symbol: 'ELCO.TA', hebrewName: 'אלקו', englishName: 'Elco', type: 'stock', exchange: 'TASE' },
    { symbol: 'ELEC.TA', hebrewName: 'אלקטרה פאוור', englishName: 'Electra Power', type: 'stock', exchange: 'TASE' },
    { symbol: 'ELIN.TA', hebrewName: 'אלעזרא', englishName: 'Elecra Real Estate', type: 'stock', exchange: 'TASE' },
    { symbol: 'ENRO.TA', hebrewName: 'האנרו', englishName: 'Hanro', type: 'stock', exchange: 'TASE' },
    { symbol: 'ERL.TA', hebrewName: 'אראל', englishName: 'Arel', type: 'stock', exchange: 'TASE' },
    { symbol: 'ESNT.TA', hebrewName: 'אשטרום נכסים', englishName: 'Ashtrom Properties', type: 'stock', exchange: 'TASE' },
    { symbol: 'EXL.TA', hebrewName: 'אקסלנס', englishName: 'Excellence', type: 'stock', exchange: 'TASE' },
    { symbol: 'GAVN.TA', hebrewName: 'גב ים', englishName: 'Gav-Yam Bayside', type: 'stock', exchange: 'TASE' },
    { symbol: 'GLOB.TA', hebrewName: 'גלובל כנפיים', englishName: 'Global Knafaim', type: 'stock', exchange: 'TASE' },
    { symbol: 'GZIT.TA', hebrewName: 'גזית גלוב', englishName: 'Gazit Globe', type: 'stock', exchange: 'TASE' },
    { symbol: 'HAGZ.TA', hebrewName: 'חגג נדלן', englishName: 'Hagag Real Estate', type: 'stock', exchange: 'TASE' },
    { symbol: 'HAS.TA', hebrewName: 'הכשרת הישוב', englishName: 'ILDC', type: 'stock', exchange: 'TASE' },
    { symbol: 'IBI.TA', hebrewName: 'אי.בי.אי בית השקעות', englishName: 'IBI Investment House', type: 'stock', exchange: 'TASE' },
    { symbol: 'ILDC.TA', hebrewName: 'הכשרת הישוב פיתוח', englishName: 'ILDC Dev', type: 'stock', exchange: 'TASE' },
    { symbol: 'ITCL.TA', hebrewName: 'איתמר מדיקל', englishName: 'Itamar Medical', type: 'stock', exchange: 'TASE' },
    { symbol: 'KAMA.TA', hebrewName: 'קרסו מוטורס', englishName: 'Carasso Motors', type: 'stock', exchange: 'TASE' },
    { symbol: 'KARD.TA', hebrewName: 'קרדן נ.ו', englishName: 'Kardan NV', type: 'stock', exchange: 'TASE' },
    { symbol: 'KLIL.TA', hebrewName: 'קליל', englishName: 'Klil', type: 'stock', exchange: 'TASE' },
    { symbol: 'MGDL.TA', hebrewName: 'מגדל ביטוח', englishName: 'Migdal Insurance', type: 'stock', exchange: 'TASE' },
    { symbol: 'MISH.TA', hebrewName: 'משק אנרגיה', englishName: 'Meshek Energy', type: 'stock', exchange: 'TASE' },
    { symbol: 'NAVS.TA', hebrewName: 'נאוויטס', englishName: 'Navitas', type: 'stock', exchange: 'TASE' },
    { symbol: 'NIO.TA', hebrewName: 'ניומד אנרגיה', englishName: 'NewMed Energy', type: 'stock', exchange: 'TASE' },
    { symbol: 'NOC.TA', hebrewName: 'נופר אנרגיה', englishName: 'Nofar Energy', type: 'stock', exchange: 'TASE' },
    { symbol: 'NVCS.TA', hebrewName: 'נובולוג', englishName: 'Novolog', type: 'stock', exchange: 'TASE' },
    { symbol: 'ODC.TA', hebrewName: 'אודיקודס', englishName: 'OdeC', type: 'stock', exchange: 'TASE' },
    { symbol: 'ONE.TA', hebrewName: 'וואן טכנולוגיות', englishName: 'One Software', type: 'stock', exchange: 'TASE' },
    { symbol: 'ORC.TA', hebrewName: 'אורכית', englishName: 'Orckit', type: 'stock', exchange: 'TASE' },
    { symbol: 'PEMG.TA', hebrewName: 'פרימיום נדלן', englishName: 'Premium Real Estate', type: 'stock', exchange: 'TASE' },
    { symbol: 'PERM.TA', hebrewName: 'פרשמרקט', englishName: 'Freshmarket', type: 'stock', exchange: 'TASE' },
    { symbol: 'PLTR.TA', hebrewName: 'פלרם', englishName: 'Palram', type: 'stock', exchange: 'TASE' },
    { symbol: 'POLY.TA', hebrewName: 'פוליגון', englishName: 'Polygon', type: 'stock', exchange: 'TASE' },
    { symbol: 'PRCM.TA', hebrewName: 'פרטנר', englishName: 'Partner Comm', type: 'stock', exchange: 'TASE' },
    { symbol: 'PRIG.TA', hebrewName: 'פריגו', englishName: 'Perrigo', type: 'stock', exchange: 'TASE' },
    { symbol: 'PROR.TA', hebrewName: 'פריורטק', englishName: 'Priortech', type: 'stock', exchange: 'TASE' },
    { symbol: 'RAD.TA', hebrewName: 'רדויזן', englishName: 'Radvision', type: 'stock', exchange: 'TASE' },
    { symbol: 'RIT.TA', hebrewName: 'ריט', englishName: 'REIT 1', type: 'stock', exchange: 'TASE' },
    { symbol: 'RNDO.TA', hebrewName: 'ראדא', englishName: 'RADA', type: 'stock', exchange: 'TASE' },
    { symbol: 'SECL.TA', hebrewName: 'שיכון ופיתוח', englishName: 'Shikun Dev', type: 'stock', exchange: 'TASE' },
    { symbol: 'SEL.TA', hebrewName: 'סלע קפיטל', englishName: 'Sela Capital', type: 'stock', exchange: 'TASE' },
    { symbol: 'SFEN.TA', hebrewName: 'ספנס', englishName: 'Safens', type: 'stock', exchange: 'TASE' },
    { symbol: 'SHAK.TA', hebrewName: 'שחם', englishName: 'Shaham', type: 'stock', exchange: 'TASE' },
    { symbol: 'SHAM.TA', hebrewName: 'שמיר', englishName: 'Shamir Optical', type: 'stock', exchange: 'TASE' },
    { symbol: 'SIRI.TA', hebrewName: 'סיריוס', englishName: 'Sirius', type: 'stock', exchange: 'TASE' },
    { symbol: 'SNIR.TA', hebrewName: 'שניר', englishName: 'Snir', type: 'stock', exchange: 'TASE' },
    { symbol: 'SRON.TA', hebrewName: 'שרין', englishName: 'Sarine Technologies', type: 'stock', exchange: 'TASE' },
    { symbol: 'TAKA.TA', hebrewName: 'תדיראן הולדינגס', englishName: 'Tadiran Holdings', type: 'stock', exchange: 'TASE' },
    { symbol: 'TECT.TA', hebrewName: 'טרם', englishName: 'Terem', type: 'stock', exchange: 'TASE' },
    { symbol: 'THRL.TA', hebrewName: 'תראלי', englishName: 'Thrali', type: 'stock', exchange: 'TASE' },
    { symbol: 'TRMO.TA', hebrewName: 'תרמו', englishName: 'Termo', type: 'stock', exchange: 'TASE' },
    { symbol: 'UML.TA', hebrewName: 'אונייטד', englishName: 'United', type: 'stock', exchange: 'TASE' },
    { symbol: 'UNV.TA', hebrewName: 'יוניברסל', englishName: 'Universal', type: 'stock', exchange: 'TASE' },
    { symbol: 'VER.TA', hebrewName: 'וריפון', englishName: 'Veriphone', type: 'stock', exchange: 'TASE' },
    { symbol: 'VIL.TA', hebrewName: 'וילאר', englishName: 'Villar', type: 'stock', exchange: 'TASE' },
    { symbol: 'YHVB.TA', hebrewName: 'יהב', englishName: 'Yahav', type: 'stock', exchange: 'TASE' },
    { symbol: 'YTRA.TA', hebrewName: 'יתרות', englishName: 'Yitrot', type: 'stock', exchange: 'TASE' }
];

const mutualFunds = [
    { symbol: 'FUND:5131417', fundId: '5131417', hebrewName: 'מיטב כספית שקלית', englishName: 'Meitav Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5131581', fundId: '5131581', hebrewName: 'מיטב כספית דולרית', englishName: 'Meitav USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5115204', fundId: '5115204', hebrewName: 'הראל כספית שקלית', englishName: 'Harel Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5105262', fundId: '5105262', hebrewName: 'אלטשולר שחם כספית שקלית', englishName: 'Altshuler Shaham Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5122739', fundId: '5122739', hebrewName: 'קסם כספית שקלית', englishName: 'Ksm Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132209', fundId: '5132209', hebrewName: 'מור כספית שקלית', englishName: 'More Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5100065', fundId: '5100065', hebrewName: 'ילין לפידות כספית', englishName: 'Yelin Lapidot Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5130757', fundId: '5130757', hebrewName: 'איילון כספית שקלית', englishName: 'Ayalon Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5104521', fundId: '5104521', hebrewName: 'מגדל כספית שקלית', englishName: 'Migdal Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5121434', fundId: '5121434', hebrewName: 'אי.בי.אי כספית שקלית', englishName: 'IBI Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:1159285', fundId: '1159285', hebrewName: 'MTF כספית', englishName: 'MTF Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5131425', fundId: '5131425', hebrewName: 'מיטב כספית ניהול נזילות', englishName: 'Meitav Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132514', fundId: '5132514', hebrewName: 'הראל כספית ניהול נזילות', englishName: 'Harel Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132399', fundId: '5132399', hebrewName: 'מגדל כספית ניהול נזילות', englishName: 'Migdal Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133603', fundId: '5133603', hebrewName: 'קסם כספית ניהול נזילות', englishName: 'Ksm Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5134106', fundId: '5134106', hebrewName: 'אי.בי.אי. כספית ניהול נזילות', englishName: 'IBI Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133488', fundId: '5133488', hebrewName: 'מור כספית ניהול נזילות', englishName: 'More Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132647', fundId: '5132647', hebrewName: 'אלטשולר שחם כספית ניהול נזילות', englishName: 'Altshuler Shaham Liquidity', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133744', fundId: '5133744', hebrewName: 'ילין לפידות כספית ניהול נזילות', englishName: 'Yelin Lapidot Liquidity', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5122713', fundId: '5122713', hebrewName: 'פסגות כספית ניהול נזילות', englishName: 'Psagot Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132480', fundId: '5132480', hebrewName: 'הראל כספית דולרית', englishName: 'Harel USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132449', fundId: '5132449', hebrewName: 'אלטשולר שחם כספית דולרית', englishName: 'Altshuler Shaham USD', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5125369', fundId: '5125369', hebrewName: 'קסם כספית דולרית', englishName: 'Ksm USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132894', fundId: '5132894', hebrewName: 'מור כספית דולרית', englishName: 'More USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133611', fundId: '5133611', hebrewName: 'ילין לפידות כספית דולרית', englishName: 'Yelin Lapidot USD', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132530', fundId: '5132530', hebrewName: 'מגדל כספית דולרית', englishName: 'Migdal USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132712', fundId: '5132712', hebrewName: 'אי.בי.אי כספית דולרית', englishName: 'IBI USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5122697', fundId: '5122697', hebrewName: 'פסגות כספית שקלית', englishName: 'Psagot Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132605', fundId: '5132605', hebrewName: 'פסגות כספית דולרית', englishName: 'Psagot USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133066', fundId: '5133066', hebrewName: 'איילון כספית דולרית', englishName: 'Ayalon USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132472', fundId: '5132472', hebrewName: 'הפניקס כספית שקלית', englishName: 'Phoenix Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132688', fundId: '5132688', hebrewName: 'הפניקס כספית דולרית', englishName: 'Phoenix USD Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133793', fundId: '5133793', hebrewName: 'הפניקס כספית ניהול נזילות', englishName: 'Phoenix Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132969', fundId: '5132969', hebrewName: 'תמיר פישמן כספית שקלית', englishName: 'Tamir Fishman Shekel', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133124', fundId: '5133124', hebrewName: 'אנליסט כספית שקלית', englishName: 'Analyst Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133884', fundId: '5133884', hebrewName: 'אנליסט כספית ניהול נזילות', englishName: 'Analyst Liquidity Management', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132803', fundId: '5132803', hebrewName: 'רוטשילד כספית שקלית', englishName: 'Rothschild Shekel Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133462', fundId: '5133462', hebrewName: 'מיטב כספית אירופית', englishName: 'Meitav EUR Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133918', fundId: '5133918', hebrewName: 'הראל כספית אירופית', englishName: 'Harel EUR Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5134015', fundId: '5134015', hebrewName: 'מגדל כספית אירו', englishName: 'Migdal EUR Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133934', fundId: '5133934', hebrewName: 'קסם כספית אירו', englishName: 'Ksm EUR Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5133504', fundId: '5133504', hebrewName: 'אי.בי.אי כספית אירו', englishName: 'IBI EUR Money Market', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132175', fundId: '5132175', hebrewName: 'מור כספית ללא מניות', englishName: 'More Money Market No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5131805', fundId: '5131805', hebrewName: 'מיטב כספית ללא חשיפה למניות', englishName: 'Meitav Money Market No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132043', fundId: '5132043', hebrewName: 'הראל כספית שקלית ללא חשיפה למניות', englishName: 'Harel Shekel No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5131912', fundId: '5131912', hebrewName: 'קסם כספית שקלית ללא חשיפה', englishName: 'Ksm Shekel No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132100', fundId: '5132100', hebrewName: 'מגדל כספית ללא חשיפה למניות', englishName: 'Migdal Money Market No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132191', fundId: '5132191', hebrewName: 'אלטשולר שחם כספית ללא מניות', englishName: 'Altshuler Shaham No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5131870', fundId: '5131870', hebrewName: 'אי.בי.אי. כספית שקלית ללא מניות', englishName: 'IBI Shekel No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132241', fundId: '5132241', hebrewName: 'ילין לפידות כספית שקלית ללא מניות', englishName: 'Yelin Lapidot Shekel No Stocks', type: 'fund', exchange: 'TASE' },
    { symbol: 'FUND:5132332', fundId: '5132332', hebrewName: 'פסגות כספית שקלית ללא חשיפה למניות', englishName: 'Psagot Shekel No Stocks', type: 'fund', exchange: 'TASE' }
];

const allData = [...ta125, ...mutualFunds];
const uniqueDataMap = new Map();
allData.forEach(item => uniqueDataMap.set(item.symbol, item));
const uniqueData = Array.from(uniqueDataMap.values());

const outPath = path.join(__dirname, 'server', 'data', 'israeliCatalog.js');
const jsContent = 'export const israeliCatalog = ' + JSON.stringify(uniqueData, null, 4) + ';\n';

fs.writeFileSync(outPath, jsContent, 'utf8');
console.log('Successfully generated full catalog with count:', uniqueData.length);
